name: Feature Request
description: Request a feature for memU-server
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see in memU-server.
      placeholder: I would like to have...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches could be...
    validations:
      required: false
  
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit memU-server users?
      placeholder: This feature would help users...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
