name: Improvement Suggestion
description: Suggest an improvement for memU-server
title: "[Improvement]: "
labels: ["improvement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please fill out the form below.
  
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: Describe the current behavior or implementation in memU-server.
      placeholder: Currently, the system...
    validations:
      required: true
  
  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: Describe the improvement you'd like to suggest.
      placeholder: It would be better if...
    validations:
      required: true
  
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why would this be an improvement? What benefits would it bring?
      placeholder: This would improve...
    validations:
      required: true
  
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What areas of memU-server would be affected by this improvement?
      placeholder: This would affect...
    validations:
      required: false
  
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how to implement this improvement, please share them.
      placeholder: This could be implemented by...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references about the improvement here.
    validations:
      required: false
